#!/usr/bin/env bash


D=$(pwd)
if [[ D == *"hack"* ]]; then
  echo ""
  echo "/hack is a special directory. These scripts should only be executed from the Makefile."
  echo "..or the directory above this one."
  echo ""
  echo "We suggest using the github.com/aurae-runtime/environment repository for building aurae"
  echo "projects from source."
  echo ""
  exit 99
fi

# This script assumes running from the top level directory within a Makefile

