#!/usr/bin/env bash


sha=$(git rev-parse HEAD)

sudo -E docker build -t krisnova/aurae:latest -t krisnova/aurae:$sha -f images/Dockerfile.nested .
sudo -E docker push krisnova/aurae:latest
sudo -E docker push krisnova/aurae:$sha


