#!/usr/bin/env bash
# ---------------------------------------------------------------------------- #
#             Apache 2.0 License Copyright © 2022 The Aurae Authors            #
#                                                                              #
#                +--------------------------------------------+                #
#                |   █████╗ ██╗   ██╗██████╗  █████╗ ███████╗ |                #
#                |  ██╔══██╗██║   ██║██╔══██╗██╔══██╗██╔════╝ |                #
#                |  ███████║██║   ██║██████╔╝███████║█████╗   |                #
#                |  ██╔══██║██║   ██║██╔══██╗██╔══██║██╔══╝   |                #
#                |  ██║  ██║╚██████╔╝██║  ██║██║  ██║███████╗ |                #
#                |  ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝ |                #
#                +--------------------------------------------+                #
#                                                                              #
#                         Distributed Systems Runtime                          #
#                                                                              #
# ---------------------------------------------------------------------------- #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
#                                                                              #
# ---------------------------------------------------------------------------- #

D=$(pwd)
if [[ $D == *"hack"* ]]; then
  echo ""
  echo "/hack is a special directory. These scripts should only be executed from the Makefile."
  echo "..or the directory above this one."
  echo ""
  echo "We suggest using the github.com/aurae-runtime/environment repository for building aurae"
  echo "projects from source."
  echo ""
  exit 99
fi

# This script assumes running from the top level directory within a Makefile

EXPECTEDSCRIPT=$(cat hack/.header.script)
EXPECTEDSOURCE=$(cat hack/.header.source)

### Define Scripts
SCRIPTS=$(find . \( \
  -iname '*.sh' -or \
  -iname '*.toml' \
    \) -not -path '*/ignore/*')

### Define Sources
SOURCES=$(find . \( \
  -iname '*.rs' -or \
  -iname '*.go' -or \
  -iname '*.c' -or \
  -iname '*.h' \
    \) -not -path '*/ignore/*')

### Rust Sources
RUSTSOURCES=$(find . \( \
  -iname '*.rs' \
    \) -not -path '*/ignore/*')