#!/usr/bin/env bash


D=$(pwd)
if [[ $D == *"hack"* ]]; then
  echo ""
  echo "/hack is a special directory. These scripts should only be executed from the Makefile."
  echo "..or the directory above this one."
  echo ""
  echo "We suggest using the github.com/aurae-runtime/environment repository for building aurae"
  echo "projects from source."
  echo ""
  exit 99
fi

# This script assumes running from the top level directory within a Makefile

EXPECTEDSCRIPT=$(cat hack/.header.script)
EXPECTEDSOURCE=$(cat hack/.header.source)

### Define Scripts
SCRIPTS=$(find . \( \
  -iname '*.sh' -or \
  -iname '*.toml' -or \
  -iname '*.yml' -or \
  -name '*.mk' -or \
  -name 'Makefile' -or \
  -name 'Dockerfile*' \
    \) -not -path '*/ignore/*')

### Define Sources
SOURCES=$(find . \( \
  -iname '*.rs' -or \
  -iname '*.go' -or \
  -iname '*.c' -or \
  -iname '*.h' -or \
  -iname '*.ts' -or \
  -iname '*.proto' \
    \) -not -path '*/ignore/*')

### Rust Sources
RUSTSOURCES=$(find . \( \
  -iname '*.rs' \
    \) -not -path '*/ignore/*' -not -path -'*/gen/*')
