#!/usr/bin/env bash
# ---------------------------------------------------------------------------- #
#                |   █████╗ ██╗   ██╗██████╗  █████╗ ███████╗ |                #
#                |  ██╔══██╗██║   ██║██╔══██╗██╔══██╗██╔════╝ |                #
#                |  ███████║██║   ██║██████╔╝███████║█████╗   |                #
#                |  ██╔══██║██║   ██║██╔══██╗██╔══██║██╔══╝   |                #
#                |  ██║  ██║╚██████╔╝██║  ██║██║  ██║███████╗ |                #
#                |  ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝ |                #
#                +--------------------------------------------+                #
#                                                                              #
#                         Distributed Systems Runtime                          #
# ---------------------------------------------------------------------------- #
# Copyright 2022 - 2024, the aurae contributors                                #
# SPDX-License-Identifier: Apache-2.0                                          #
# ---------------------------------------------------------------------------- #

D=$(pwd)
if [[ $D == *"hack"* ]]; then
  echo ""
  echo "/hack is a special directory. These scripts should only be executed from the Makefile."
  echo "..or the directory above this one."
  echo ""
  exit 99
fi

# This script assumes running from the top level directory within a Makefile

EXPECTEDSCRIPT=$(cat hack/.header.script)
EXPECTEDSOURCE=$(cat hack/.header.source)

### Define Scripts
SCRIPTS=$(find . \( \
  -iname '*.sh' -or \
  -iname '*.toml' \
    \) -not -path '*/ignore/*')

### HACK Dir Scripts
HACKSCRIPTS=$(find -s hack -type f -not \( \
  -name 'certgen.client.ext' -or \
  -name 'certgen.server.ext' -or \
  -name '.header.script' -or \
  -name '.header.source' \
    \))

### Define Sources
SOURCES=$(find . \( \
  -iname '*.rs' -or \
  -iname '*.go' -or \
  -iname '*.c' -or \
  -iname '*.h' \
    \) -not -path '*/ignore/*')

### Rust Sources
RUSTSOURCES=$(find . \( \
  -iname '*.rs' \
    \) -not -path '*/ignore/*' -not -path -'*/gen/*')
