#!/usr/bin/env bash


D=$(pwd)
if [[ $D == *"hack"* ]]; then
  echo ""
  echo "/hack is a special directory. These scripts should only be executed from the Makefile."
  echo "..or the directory above this one."
  echo ""
  echo "We suggest using the github.com/aurae-runtime/environment repository for building aurae"
  echo "projects from source."
  echo ""
  exit 99
fi

# This script assumes running from the top level directory within a Makefile

. hack/file-definitions

### Check Scripts
echo ""
echo " [ Checking Scripts ] "
echo ""
for SCRIPT in $SCRIPTS; do
    
    #Check if first line is shebang
    if [[ $(head -c 2 "$SCRIPT") == "#!" ]]
    then
      #Grab the 30 lines after the shebang
      HEADER=$(tail -n+2 "$SCRIPT" | head -n 30)
    else
      HEADER=$(head -n 30 "$SCRIPT")
    fi

    
    if [ "$HEADER" != "$EXPECTEDSCRIPT" ]; then
      echo "  -> [FAILED SCRIPT FILE] Invalid header: $SCRIPT"
      STATUS=1
    fi
done

### Check Source Files
echo " [ Checking Source Code ] "
echo ""
for SOURCE in $SOURCES; do

    # Bypass files here
    if [ "$SOURCE" == "ignore.me" ]; then
        continue
    fi

    #Check if first line is shebang
    if [[ $(head -c 2 "$SOURCE") == "#!" ]]
    then
      #Grab the 30 lines after the shebang
      HEADER=$(tail -n+2 "$SOURCE" | head -n 30)
    else
      HEADER=$(head -n 30 "$SOURCE")
    fi

    if [ "$HEADER" != "$EXPECTEDSOURCE" ]; then
      echo "  -> [FAILED SOURCE FILE] Invalid header: $SOURCE"
      STATUS=1
    fi

done

echo " [ Checks Complete ] "

exit $STATUS