#!/usr/bin/env bash
# ---------------------------------------------------------------------------- #
#                |   █████╗ ██╗   ██╗██████╗  █████╗ ███████╗ |                #
#                |  ██╔══██╗██║   ██║██╔══██╗██╔══██╗██╔════╝ |                #
#                |  ███████║██║   ██║██████╔╝███████║█████╗   |                #
#                |  ██╔══██║██║   ██║██╔══██╗██╔══██║██╔══╝   |                #
#                |  ██║  ██║╚██████╔╝██║  ██║██║  ██║███████╗ |                #
#                |  ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝ |                #
#                +--------------------------------------------+                #
#                                                                              #
#                         Distributed Systems Runtime                          #
# ---------------------------------------------------------------------------- #
# Copyright 2022 - 2024, the aurae contributors                                #
# SPDX-License-Identifier: Apache-2.0                                          #
# ---------------------------------------------------------------------------- #

D=$(pwd)
if [[ $D == *"hack"* ]]; then
  echo ""
  echo "/hack is a special directory. These scripts should only be executed from the Makefile."
  echo "..or the directory above this one."
  echo ""
  exit 99
fi

# This script assumes running from the top level directory within a Makefile

. hack/file-definitions

status=0

### Check Scripts
echo ""
echo " [ Checking Scripts ] "
echo ""
for SCRIPT in $SCRIPTS; do
    # Bypass files here
    if [ "$SCRIPT" == "ignore.me" ]; then
        continue
    fi

    # Replace the actual year with DATE so we can ignore the year when checking for the license header.
    HEADER=$(head -n 30 $SCRIPT | sed -E -e 's/Copyright © [0-9]+/Copyright © DATE/')
    if [ "$HEADER" != "$EXPECTEDSCRIPT" ]; then
      echo "  -> [FAILED SCRIPT FILE] Invalid header: $SCRIPT"
      STATUS=1
    fi
done

### Check Source Files
echo " [ Checking Source Code ] "
echo ""
for SOURCE in $SOURCES; do

    # Bypass files here
    if [ "$SOURCE" == "ignore.me" ]; then
        continue
    fi

    # Replace the actual year with DATE so we can ignore the year when checking for the license header.
    #HEADER=$(head -n 30 $SOURCE | sed -E -e 's/Copyright © [0-9]+/Copyright © DATE/')
    if [ "$HEADER" != "$EXPECTEDSOURCE" ]; then
      echo "  -> [FAILED SOURCE FILE] Invalid header: $SOURCE"
      STATUS=1
    fi

done

echo " [ Checks Complete ] "

exit $STATUS
