#!/usr/bin/env bash


D=$(pwd)
if [[ $D == *"hack"* ]]; then
  echo ""
  echo "/hack is a special directory. These scripts should only be executed from the Makefile."
  echo "..or the directory above this one."
  echo ""
  echo "We suggest using the github.com/aurae-runtime/environment repository for building aurae"
  echo "projects from source."
  echo ""
  exit 99
fi

# This script assumes running from the top level directory within a Makefile

. hack/file-definitions

### Write Scripts
echo ""
echo " [ Checking Scripts ] "
echo ""
for FILE in $SCRIPTS; do

    # Bypass files here
    if [ "$FILE" == "ignore.me" ]; then
        continue
    fi

    if [[ $(head -c 2 "$FILE") == "#!" ]]
    then
      SHEBANG="$(head -n 1 "$FILE")\n"
      SRC="$(tail -n +32 "$FILE")"
      CONTENT=$(tail -n+2 "$FILE" | head -n 30)
    else
      SHEBANG=""
      SRC="$(cat $FILE)"
      CONTENT=$(head -n 30 $FILE)
    fi

    if [ "$CONTENT" != "$EXPECTEDSCRIPT" ]; then
		  echo -e "$SHEBANG$EXPECTEDSCRIPT\n\n$SRC" > "$FILE"
      echo "  -> [MUTATING SOURCE FILE] Writing header: $FILE"
    fi

done

### Write Source Files (.rs, .go, .c, etc)
echo " [ Checking Source Code ] "
echo ""
for FILE in $SOURCES; do

    # Bypass files here
    if [ "$FILE" == "ignore.me" ]; then
      continue
    fi

    if [[ $(head -c 2 "$FILE") == "#!" ]]
    then
      SHEBANG="$(head -n 1 "$FILE")\n"
      SRC="$(tail -n +31 "$FILE")"
      CONTENT=$(tail -n+2 "$FILE" | head -n 30)
    else
      SHEBANG=""
      SRC="$(cat $FILE)"
      CONTENT=$(head -n 30 $FILE)
    fi

    if [ "$CONTENT" != "$EXPECTEDSOURCE" ]; then
		  echo -e "$SHEBANG$EXPECTEDSOURCE\n\n$SRC" > "$FILE"
      echo "  -> [MUTATING SOURCE FILE] Writing header: $FILE"
    fi

done

echo " [ Write Complete] "

echo $status

