#!/usr/bin/env bash


rm -rf target/busybox
mkdir -p target/busybox/rootfs
sudo -E docker pull busybox
sudo -E docker create --name busybox-aurae busybox
sudo -E docker export busybox-aurae | tar -C target/busybox/rootfs -xf -
sudo -E docker rm busybox-aurae
cd target/busybox
sudo -E runc spec