#!/usr/bin/env bash


CID="aurae-spawn-hack"
BUNDLE="target/aurae-spawn"

# [Spawn]
# Assume we are running in the root top level directory
# Assume we must create "aurae-spawn" as this is hard coded in auraed
sudo -E auraed spawn --output ${BUNDLE}

# [Run/Debug]
echo "Delete:   ${CID}"
sudo -E youki delete ${CID}

echo "Create:   ${CID}"
sudo -E youki create --bundle ${BUNDLE} ${CID}

echo "Start :   ${CID}"
sudo -E youki start ${CID}
