// -------------------------------------------------------------------------- *\
//             Apache 2.0 License Copyright © 2022 The Aurae Authors          *
//                                                                            *
//                +--------------------------------------------+              *
//                |   █████╗ ██╗   ██╗██████╗  █████╗ ███████╗ |              *
//                |  ██╔══██╗██║   ██║██╔══██╗██╔══██╗██╔════╝ |              *
//                |  ███████║██║   ██║██████╔╝███████║█████╗   |              *
//                |  ██╔══██║██║   ██║██╔══██╗██╔══██║██╔══╝   |              *
//                |  ██║  ██║╚██████╔╝██║  ██║██║  ██║███████╗ |              *
//                |  ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝ |              *
//                +--------------------------------------------+              *
//                                                                            *
//                         Distributed Systems Runtime                        *
//                                                                            *
// -------------------------------------------------------------------------- *
//                                                                            *
//   Licensed under the Apache License, Version 2.0 (the "License");          *
//   you may not use this file except in compliance with the License.         *
//   You may obtain a copy of the License at                                  *
//                                                                            *
//       http://www.apache.org/licenses/LICENSE-2.0                           *
//                                                                            *
//   Unless required by applicable law or agreed to in writing, software      *
//   distributed under the License is distributed on an "AS IS" BASIS,        *
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. *
//   See the License for the specific language governing permissions and      *
//   limitations under the License.                                           *
//                                                                            *
//\* --------------------------------------------------------------------------

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: runtime/pod/v0/pod.proto

package podv0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PodServiceAllocateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PodServiceAllocateRequest) Reset() {
	*x = PodServiceAllocateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_pod_v0_pod_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodServiceAllocateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodServiceAllocateRequest) ProtoMessage() {}

func (x *PodServiceAllocateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_pod_v0_pod_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodServiceAllocateRequest.ProtoReflect.Descriptor instead.
func (*PodServiceAllocateRequest) Descriptor() ([]byte, []int) {
	return file_runtime_pod_v0_pod_proto_rawDescGZIP(), []int{0}
}

type PodServiceAllocateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PodServiceAllocateResponse) Reset() {
	*x = PodServiceAllocateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_pod_v0_pod_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodServiceAllocateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodServiceAllocateResponse) ProtoMessage() {}

func (x *PodServiceAllocateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_pod_v0_pod_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodServiceAllocateResponse.ProtoReflect.Descriptor instead.
func (*PodServiceAllocateResponse) Descriptor() ([]byte, []int) {
	return file_runtime_pod_v0_pod_proto_rawDescGZIP(), []int{1}
}

type PodServiceFreeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PodServiceFreeRequest) Reset() {
	*x = PodServiceFreeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_pod_v0_pod_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodServiceFreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodServiceFreeRequest) ProtoMessage() {}

func (x *PodServiceFreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_pod_v0_pod_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodServiceFreeRequest.ProtoReflect.Descriptor instead.
func (*PodServiceFreeRequest) Descriptor() ([]byte, []int) {
	return file_runtime_pod_v0_pod_proto_rawDescGZIP(), []int{2}
}

type PodServiceFreeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PodServiceFreeResponse) Reset() {
	*x = PodServiceFreeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_pod_v0_pod_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodServiceFreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodServiceFreeResponse) ProtoMessage() {}

func (x *PodServiceFreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_pod_v0_pod_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodServiceFreeResponse.ProtoReflect.Descriptor instead.
func (*PodServiceFreeResponse) Descriptor() ([]byte, []int) {
	return file_runtime_pod_v0_pod_proto_rawDescGZIP(), []int{3}
}

type Pod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Pod) Reset() {
	*x = Pod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_pod_v0_pod_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pod) ProtoMessage() {}

func (x *Pod) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_pod_v0_pod_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pod.ProtoReflect.Descriptor instead.
func (*Pod) Descriptor() ([]byte, []int) {
	return file_runtime_pod_v0_pod_proto_rawDescGZIP(), []int{4}
}

type PodServiceStartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PodServiceStartRequest) Reset() {
	*x = PodServiceStartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_pod_v0_pod_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodServiceStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodServiceStartRequest) ProtoMessage() {}

func (x *PodServiceStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_pod_v0_pod_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodServiceStartRequest.ProtoReflect.Descriptor instead.
func (*PodServiceStartRequest) Descriptor() ([]byte, []int) {
	return file_runtime_pod_v0_pod_proto_rawDescGZIP(), []int{5}
}

type PodServiceStartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PodServiceStartResponse) Reset() {
	*x = PodServiceStartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_pod_v0_pod_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodServiceStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodServiceStartResponse) ProtoMessage() {}

func (x *PodServiceStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_pod_v0_pod_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodServiceStartResponse.ProtoReflect.Descriptor instead.
func (*PodServiceStartResponse) Descriptor() ([]byte, []int) {
	return file_runtime_pod_v0_pod_proto_rawDescGZIP(), []int{6}
}

type PodServiceStopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PodServiceStopRequest) Reset() {
	*x = PodServiceStopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_pod_v0_pod_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodServiceStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodServiceStopRequest) ProtoMessage() {}

func (x *PodServiceStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_pod_v0_pod_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodServiceStopRequest.ProtoReflect.Descriptor instead.
func (*PodServiceStopRequest) Descriptor() ([]byte, []int) {
	return file_runtime_pod_v0_pod_proto_rawDescGZIP(), []int{7}
}

type PodServiceStopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PodServiceStopResponse) Reset() {
	*x = PodServiceStopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_pod_v0_pod_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodServiceStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodServiceStopResponse) ProtoMessage() {}

func (x *PodServiceStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_pod_v0_pod_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodServiceStopResponse.ProtoReflect.Descriptor instead.
func (*PodServiceStopResponse) Descriptor() ([]byte, []int) {
	return file_runtime_pod_v0_pod_proto_rawDescGZIP(), []int{8}
}

type Container struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Container) Reset() {
	*x = Container{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_pod_v0_pod_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_pod_v0_pod_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_runtime_pod_v0_pod_proto_rawDescGZIP(), []int{9}
}

var File_runtime_pod_v0_pod_proto protoreflect.FileDescriptor

var file_runtime_pod_v0_pod_proto_rawDesc = []byte{
	0x0a, 0x18, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2f, 0x70, 0x6f, 0x64, 0x2f, 0x76, 0x30,
	0x2f, 0x70, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x61, 0x75, 0x72, 0x61,
	0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x70, 0x6f, 0x64, 0x2e, 0x76, 0x30,
	0x22, 0x1b, 0x0a, 0x19, 0x50, 0x6f, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x6c,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1c, 0x0a,
	0x1a, 0x50, 0x6f, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x6c, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x50,
	0x6f, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x46, 0x72, 0x65, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x50, 0x6f, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x46, 0x72, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x05,
	0x0a, 0x03, 0x50, 0x6f, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x50, 0x6f, 0x64, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x19, 0x0a, 0x17, 0x50, 0x6f, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x50, 0x6f,
	0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x50, 0x6f, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x0b, 0x0a,
	0x09, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x32, 0xaf, 0x03, 0x0a, 0x0a, 0x50,
	0x6f, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6f, 0x0a, 0x08, 0x41, 0x6c, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x65, 0x12, 0x2f, 0x2e, 0x61, 0x75, 0x72, 0x61, 0x65, 0x2e, 0x72, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x70, 0x6f, 0x64, 0x2e, 0x76, 0x30, 0x2e, 0x50, 0x6f, 0x64,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x61, 0x75, 0x72, 0x61, 0x65, 0x2e, 0x72,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x70, 0x6f, 0x64, 0x2e, 0x76, 0x30, 0x2e, 0x50, 0x6f,
	0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x66, 0x0a, 0x05, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x12, 0x2c, 0x2e, 0x61, 0x75, 0x72, 0x61, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x2e, 0x70, 0x6f, 0x64, 0x2e, 0x76, 0x30, 0x2e, 0x50, 0x6f, 0x64, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2d, 0x2e, 0x61, 0x75, 0x72, 0x61, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x2e, 0x70, 0x6f, 0x64, 0x2e, 0x76, 0x30, 0x2e, 0x50, 0x6f, 0x64, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x63, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x2b, 0x2e, 0x61, 0x75, 0x72,
	0x61, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x70, 0x6f, 0x64, 0x2e, 0x76,
	0x30, 0x2e, 0x50, 0x6f, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x6f, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x61, 0x75, 0x72, 0x61, 0x65, 0x2e,
	0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x70, 0x6f, 0x64, 0x2e, 0x76, 0x30, 0x2e, 0x50,
	0x6f, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x63, 0x0a, 0x04, 0x46, 0x72, 0x65, 0x65, 0x12,
	0x2b, 0x2e, 0x61, 0x75, 0x72, 0x61, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e,
	0x70, 0x6f, 0x64, 0x2e, 0x76, 0x30, 0x2e, 0x50, 0x6f, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x46, 0x72, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x61,
	0x75, 0x72, 0x61, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x70, 0x6f, 0x64,
	0x2e, 0x76, 0x30, 0x2e, 0x50, 0x6f, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x46, 0x72,
	0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x47, 0x5a, 0x45,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x75, 0x72, 0x61, 0x65,
	0x2d, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2f, 0x61, 0x75, 0x72, 0x61, 0x65, 0x2f, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2f, 0x70, 0x6f, 0x64, 0x2f, 0x76, 0x30, 0x3b,
	0x70, 0x6f, 0x64, 0x76, 0x30, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_runtime_pod_v0_pod_proto_rawDescOnce sync.Once
	file_runtime_pod_v0_pod_proto_rawDescData = file_runtime_pod_v0_pod_proto_rawDesc
)

func file_runtime_pod_v0_pod_proto_rawDescGZIP() []byte {
	file_runtime_pod_v0_pod_proto_rawDescOnce.Do(func() {
		file_runtime_pod_v0_pod_proto_rawDescData = protoimpl.X.CompressGZIP(file_runtime_pod_v0_pod_proto_rawDescData)
	})
	return file_runtime_pod_v0_pod_proto_rawDescData
}

var file_runtime_pod_v0_pod_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_runtime_pod_v0_pod_proto_goTypes = []interface{}{
	(*PodServiceAllocateRequest)(nil),  // 0: aurae.runtime.pod.v0.PodServiceAllocateRequest
	(*PodServiceAllocateResponse)(nil), // 1: aurae.runtime.pod.v0.PodServiceAllocateResponse
	(*PodServiceFreeRequest)(nil),      // 2: aurae.runtime.pod.v0.PodServiceFreeRequest
	(*PodServiceFreeResponse)(nil),     // 3: aurae.runtime.pod.v0.PodServiceFreeResponse
	(*Pod)(nil),                        // 4: aurae.runtime.pod.v0.Pod
	(*PodServiceStartRequest)(nil),     // 5: aurae.runtime.pod.v0.PodServiceStartRequest
	(*PodServiceStartResponse)(nil),    // 6: aurae.runtime.pod.v0.PodServiceStartResponse
	(*PodServiceStopRequest)(nil),      // 7: aurae.runtime.pod.v0.PodServiceStopRequest
	(*PodServiceStopResponse)(nil),     // 8: aurae.runtime.pod.v0.PodServiceStopResponse
	(*Container)(nil),                  // 9: aurae.runtime.pod.v0.Container
}
var file_runtime_pod_v0_pod_proto_depIdxs = []int32{
	0, // 0: aurae.runtime.pod.v0.PodService.Allocate:input_type -> aurae.runtime.pod.v0.PodServiceAllocateRequest
	5, // 1: aurae.runtime.pod.v0.PodService.Start:input_type -> aurae.runtime.pod.v0.PodServiceStartRequest
	7, // 2: aurae.runtime.pod.v0.PodService.Stop:input_type -> aurae.runtime.pod.v0.PodServiceStopRequest
	2, // 3: aurae.runtime.pod.v0.PodService.Free:input_type -> aurae.runtime.pod.v0.PodServiceFreeRequest
	1, // 4: aurae.runtime.pod.v0.PodService.Allocate:output_type -> aurae.runtime.pod.v0.PodServiceAllocateResponse
	6, // 5: aurae.runtime.pod.v0.PodService.Start:output_type -> aurae.runtime.pod.v0.PodServiceStartResponse
	8, // 6: aurae.runtime.pod.v0.PodService.Stop:output_type -> aurae.runtime.pod.v0.PodServiceStopResponse
	3, // 7: aurae.runtime.pod.v0.PodService.Free:output_type -> aurae.runtime.pod.v0.PodServiceFreeResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_runtime_pod_v0_pod_proto_init() }
func file_runtime_pod_v0_pod_proto_init() {
	if File_runtime_pod_v0_pod_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_runtime_pod_v0_pod_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodServiceAllocateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_pod_v0_pod_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodServiceAllocateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_pod_v0_pod_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodServiceFreeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_pod_v0_pod_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodServiceFreeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_pod_v0_pod_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_pod_v0_pod_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodServiceStartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_pod_v0_pod_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodServiceStartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_pod_v0_pod_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodServiceStopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_pod_v0_pod_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodServiceStopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_pod_v0_pod_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Container); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_runtime_pod_v0_pod_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtime_pod_v0_pod_proto_goTypes,
		DependencyIndexes: file_runtime_pod_v0_pod_proto_depIdxs,
		MessageInfos:      file_runtime_pod_v0_pod_proto_msgTypes,
	}.Build()
	File_runtime_pod_v0_pod_proto = out.File
	file_runtime_pod_v0_pod_proto_rawDesc = nil
	file_runtime_pod_v0_pod_proto_goTypes = nil
	file_runtime_pod_v0_pod_proto_depIdxs = nil
}
