// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: runtime/pod/v0/pod.proto

package podv0

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PodServiceClient is the client API for PodService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PodServiceClient interface {
	Allocate(ctx context.Context, in *PodServiceAllocateRequest, opts ...grpc.CallOption) (*PodServiceAllocateResponse, error)
	Start(ctx context.Context, in *PodServiceStartRequest, opts ...grpc.CallOption) (*PodServiceStartResponse, error)
	Stop(ctx context.Context, in *PodServiceStopRequest, opts ...grpc.CallOption) (*PodServiceStopResponse, error)
	Free(ctx context.Context, in *PodServiceFreeRequest, opts ...grpc.CallOption) (*PodServiceFreeResponse, error)
}

type podServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPodServiceClient(cc grpc.ClientConnInterface) PodServiceClient {
	return &podServiceClient{cc}
}

func (c *podServiceClient) Allocate(ctx context.Context, in *PodServiceAllocateRequest, opts ...grpc.CallOption) (*PodServiceAllocateResponse, error) {
	out := new(PodServiceAllocateResponse)
	err := c.cc.Invoke(ctx, "/aurae.runtime.pod.v0.PodService/Allocate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podServiceClient) Start(ctx context.Context, in *PodServiceStartRequest, opts ...grpc.CallOption) (*PodServiceStartResponse, error) {
	out := new(PodServiceStartResponse)
	err := c.cc.Invoke(ctx, "/aurae.runtime.pod.v0.PodService/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podServiceClient) Stop(ctx context.Context, in *PodServiceStopRequest, opts ...grpc.CallOption) (*PodServiceStopResponse, error) {
	out := new(PodServiceStopResponse)
	err := c.cc.Invoke(ctx, "/aurae.runtime.pod.v0.PodService/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podServiceClient) Free(ctx context.Context, in *PodServiceFreeRequest, opts ...grpc.CallOption) (*PodServiceFreeResponse, error) {
	out := new(PodServiceFreeResponse)
	err := c.cc.Invoke(ctx, "/aurae.runtime.pod.v0.PodService/Free", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PodServiceServer is the server API for PodService service.
// All implementations must embed UnimplementedPodServiceServer
// for forward compatibility
type PodServiceServer interface {
	Allocate(context.Context, *PodServiceAllocateRequest) (*PodServiceAllocateResponse, error)
	Start(context.Context, *PodServiceStartRequest) (*PodServiceStartResponse, error)
	Stop(context.Context, *PodServiceStopRequest) (*PodServiceStopResponse, error)
	Free(context.Context, *PodServiceFreeRequest) (*PodServiceFreeResponse, error)
	mustEmbedUnimplementedPodServiceServer()
}

// UnimplementedPodServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPodServiceServer struct {
}

func (UnimplementedPodServiceServer) Allocate(context.Context, *PodServiceAllocateRequest) (*PodServiceAllocateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Allocate not implemented")
}
func (UnimplementedPodServiceServer) Start(context.Context, *PodServiceStartRequest) (*PodServiceStartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedPodServiceServer) Stop(context.Context, *PodServiceStopRequest) (*PodServiceStopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedPodServiceServer) Free(context.Context, *PodServiceFreeRequest) (*PodServiceFreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Free not implemented")
}
func (UnimplementedPodServiceServer) mustEmbedUnimplementedPodServiceServer() {}

// UnsafePodServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PodServiceServer will
// result in compilation errors.
type UnsafePodServiceServer interface {
	mustEmbedUnimplementedPodServiceServer()
}

func RegisterPodServiceServer(s grpc.ServiceRegistrar, srv PodServiceServer) {
	s.RegisterService(&PodService_ServiceDesc, srv)
}

func _PodService_Allocate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PodServiceAllocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodServiceServer).Allocate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aurae.runtime.pod.v0.PodService/Allocate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodServiceServer).Allocate(ctx, req.(*PodServiceAllocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PodServiceStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aurae.runtime.pod.v0.PodService/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodServiceServer).Start(ctx, req.(*PodServiceStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PodServiceStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aurae.runtime.pod.v0.PodService/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodServiceServer).Stop(ctx, req.(*PodServiceStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PodService_Free_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PodServiceFreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodServiceServer).Free(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aurae.runtime.pod.v0.PodService/Free",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodServiceServer).Free(ctx, req.(*PodServiceFreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PodService_ServiceDesc is the grpc.ServiceDesc for PodService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PodService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aurae.runtime.pod.v0.PodService",
	HandlerType: (*PodServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Allocate",
			Handler:    _PodService_Allocate_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _PodService_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _PodService_Stop_Handler,
		},
		{
			MethodName: "Free",
			Handler:    _PodService_Free_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "runtime/pod/v0/pod.proto",
}
