// -------------------------------------------------------------------------- *\
//             Apache 2.0 License Copyright © 2022 The Aurae Authors          *
//                                                                            *
//                +--------------------------------------------+              *
//                |   █████╗ ██╗   ██╗██████╗  █████╗ ███████╗ |              *
//                |  ██╔══██╗██║   ██║██╔══██╗██╔══██╗██╔════╝ |              *
//                |  ███████║██║   ██║██████╔╝███████║█████╗   |              *
//                |  ██╔══██║██║   ██║██╔══██╗██╔══██║██╔══╝   |              *
//                |  ██║  ██║╚██████╔╝██║  ██║██║  ██║███████╗ |              *
//                |  ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝ |              *
//                +--------------------------------------------+              *
//                                                                            *
//                         Distributed Systems Runtime                        *
//                                                                            *
// -------------------------------------------------------------------------- *
//                                                                            *
//   Licensed under the Apache License, Version 2.0 (the "License");          *
//   you may not use this file except in compliance with the License.         *
//   You may obtain a copy of the License at                                  *
//                                                                            *
//       http://www.apache.org/licenses/LICENSE-2.0                           *
//                                                                            *
//   Unless required by applicable law or agreed to in writing, software      *
//   distributed under the License is distributed on an "AS IS" BASIS,        *
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. *
//   See the License for the specific language governing permissions and      *
//   limitations under the License.                                           *
//                                                                            *
//\* --------------------------------------------------------------------------

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: runtime/cell/v0/cell.proto

package cellv0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// / The most primitive workload in Aurae, a standard executable process.
type Executable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Command     string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Executable) Reset() {
	*x = Executable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_cell_v0_cell_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Executable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Executable) ProtoMessage() {}

func (x *Executable) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_cell_v0_cell_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Executable.ProtoReflect.Descriptor instead.
func (*Executable) Descriptor() ([]byte, []int) {
	return file_runtime_cell_v0_cell_proto_rawDescGZIP(), []int{0}
}

func (x *Executable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Executable) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Executable) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// / An isolation resource used to divide a system into smaller resource
// / boundaries.
type Cell struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// / Resource parameters for control groups (cgroups)
	// / Build on the [cgroups-rs](https://github.com/kata-containers/cgroups-rs)
	// / crate. See
	// / [examples](https://github.com/kata-containers/cgroups-rs/blob/main/tests/builder.rs)
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// / A comma-separated list of CPU IDs where the task in the control group
	// / can run. Dashes between numbers indicate ranges.
	CpuCpus string `protobuf:"bytes,2,opt,name=cpu_cpus,json=cpuCpus,proto3" json:"cpu_cpus,omitempty"`
	// /  Cgroups can be guaranteed a minimum number of "CPU shares"
	// /  when a system is busy.  This does not limit a cgroup's CPU
	// /  usage if the CPUs are not busy.  For further information,
	// /  see Documentation/scheduler/sched-design-CFS.rst (or
	// /  Documentation/scheduler/sched-design-CFS.txt in Linux 5.2
	// /  and earlier).
	// /
	// / Weight of how much of the total CPU time should this control
	// /  group get. Note that this is hierarchical, so this is weighted
	// /  against the siblings of this control group.
	CpuShares uint64 `protobuf:"varint,3,opt,name=cpu_shares,json=cpuShares,proto3" json:"cpu_shares,omitempty"`
	// / Same syntax as the cpus field of this structure, but applies to
	// /  memory nodes instead of processors.
	CpuMems string `protobuf:"bytes,4,opt,name=cpu_mems,json=cpuMems,proto3" json:"cpu_mems,omitempty"`
	// / In one period, how much can the tasks run in microseconds.
	CpuQuota int64 `protobuf:"varint,5,opt,name=cpu_quota,json=cpuQuota,proto3" json:"cpu_quota,omitempty"`
	// / Linux namespaces to share with the calling process.
	// / If all values are set to false, the resulting cell
	// / will be as isolated as possible.
	// /
	// / Each shared namespace is a potential security risk.
	NsShareMount  bool `protobuf:"varint,10,opt,name=ns_share_mount,json=nsShareMount,proto3" json:"ns_share_mount,omitempty"`
	NsShareUts    bool `protobuf:"varint,11,opt,name=ns_share_uts,json=nsShareUts,proto3" json:"ns_share_uts,omitempty"`
	NsShareIpc    bool `protobuf:"varint,12,opt,name=ns_share_ipc,json=nsShareIpc,proto3" json:"ns_share_ipc,omitempty"`
	NsSharePid    bool `protobuf:"varint,13,opt,name=ns_share_pid,json=nsSharePid,proto3" json:"ns_share_pid,omitempty"`
	NsShareNet    bool `protobuf:"varint,14,opt,name=ns_share_net,json=nsShareNet,proto3" json:"ns_share_net,omitempty"`
	NsShareCgroup bool `protobuf:"varint,15,opt,name=ns_share_cgroup,json=nsShareCgroup,proto3" json:"ns_share_cgroup,omitempty"`
}

func (x *Cell) Reset() {
	*x = Cell{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_cell_v0_cell_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cell) ProtoMessage() {}

func (x *Cell) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_cell_v0_cell_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cell.ProtoReflect.Descriptor instead.
func (*Cell) Descriptor() ([]byte, []int) {
	return file_runtime_cell_v0_cell_proto_rawDescGZIP(), []int{1}
}

func (x *Cell) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cell) GetCpuCpus() string {
	if x != nil {
		return x.CpuCpus
	}
	return ""
}

func (x *Cell) GetCpuShares() uint64 {
	if x != nil {
		return x.CpuShares
	}
	return 0
}

func (x *Cell) GetCpuMems() string {
	if x != nil {
		return x.CpuMems
	}
	return ""
}

func (x *Cell) GetCpuQuota() int64 {
	if x != nil {
		return x.CpuQuota
	}
	return 0
}

func (x *Cell) GetNsShareMount() bool {
	if x != nil {
		return x.NsShareMount
	}
	return false
}

func (x *Cell) GetNsShareUts() bool {
	if x != nil {
		return x.NsShareUts
	}
	return false
}

func (x *Cell) GetNsShareIpc() bool {
	if x != nil {
		return x.NsShareIpc
	}
	return false
}

func (x *Cell) GetNsSharePid() bool {
	if x != nil {
		return x.NsSharePid
	}
	return false
}

func (x *Cell) GetNsShareNet() bool {
	if x != nil {
		return x.NsShareNet
	}
	return false
}

func (x *Cell) GetNsShareCgroup() bool {
	if x != nil {
		return x.NsShareCgroup
	}
	return false
}

// / An Aurae cell is a name given to Linux control groups (cgroups) that also include
// / a name, and special pre-exec functionality that is executed from within the same context
// / as any executables scheduled.
// /
// / A cell must be allocated for every executable scheduled. A cell defines the resource
// / constraints of the system to allocate for an arbitrary use case.
type CellServiceAllocateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// / A smaller resource constrained section of the system.
	Cell *Cell `protobuf:"bytes,1,opt,name=cell,proto3" json:"cell,omitempty"`
}

func (x *CellServiceAllocateRequest) Reset() {
	*x = CellServiceAllocateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_cell_v0_cell_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CellServiceAllocateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellServiceAllocateRequest) ProtoMessage() {}

func (x *CellServiceAllocateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_cell_v0_cell_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellServiceAllocateRequest.ProtoReflect.Descriptor instead.
func (*CellServiceAllocateRequest) Descriptor() ([]byte, []int) {
	return file_runtime_cell_v0_cell_proto_rawDescGZIP(), []int{2}
}

func (x *CellServiceAllocateRequest) GetCell() *Cell {
	if x != nil {
		return x.Cell
	}
	return nil
}

// / The response after a cell has been allocated.
type CellServiceAllocateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CellName string `protobuf:"bytes,1,opt,name=cell_name,json=cellName,proto3" json:"cell_name,omitempty"`
	// / A bool that will be set to true if the cgroup was created with
	// / cgroup v2 controller.
	CgroupV2 bool `protobuf:"varint,2,opt,name=cgroup_v2,json=cgroupV2,proto3" json:"cgroup_v2,omitempty"`
}

func (x *CellServiceAllocateResponse) Reset() {
	*x = CellServiceAllocateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_cell_v0_cell_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CellServiceAllocateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellServiceAllocateResponse) ProtoMessage() {}

func (x *CellServiceAllocateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_cell_v0_cell_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellServiceAllocateResponse.ProtoReflect.Descriptor instead.
func (*CellServiceAllocateResponse) Descriptor() ([]byte, []int) {
	return file_runtime_cell_v0_cell_proto_rawDescGZIP(), []int{3}
}

func (x *CellServiceAllocateResponse) GetCellName() string {
	if x != nil {
		return x.CellName
	}
	return ""
}

func (x *CellServiceAllocateResponse) GetCgroupV2() bool {
	if x != nil {
		return x.CgroupV2
	}
	return false
}

// / Used to remove or free a cell after it has been allocated.
type CellServiceFreeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CellName string `protobuf:"bytes,1,opt,name=cell_name,json=cellName,proto3" json:"cell_name,omitempty"`
}

func (x *CellServiceFreeRequest) Reset() {
	*x = CellServiceFreeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_cell_v0_cell_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CellServiceFreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellServiceFreeRequest) ProtoMessage() {}

func (x *CellServiceFreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_cell_v0_cell_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellServiceFreeRequest.ProtoReflect.Descriptor instead.
func (*CellServiceFreeRequest) Descriptor() ([]byte, []int) {
	return file_runtime_cell_v0_cell_proto_rawDescGZIP(), []int{4}
}

func (x *CellServiceFreeRequest) GetCellName() string {
	if x != nil {
		return x.CellName
	}
	return ""
}

// / Response after removing or freeing a cell.
type CellServiceFreeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CellServiceFreeResponse) Reset() {
	*x = CellServiceFreeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_cell_v0_cell_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CellServiceFreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellServiceFreeResponse) ProtoMessage() {}

func (x *CellServiceFreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_cell_v0_cell_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellServiceFreeResponse.ProtoReflect.Descriptor instead.
func (*CellServiceFreeResponse) Descriptor() ([]byte, []int) {
	return file_runtime_cell_v0_cell_proto_rawDescGZIP(), []int{5}
}

// / A request for starting an executable inside of a Cell.
// /
// / This is the lowest level of raw executive functionality.
// / Here you can define shell commands, and meta information about the command.
// / An executable is started synchronously.
type CellServiceStartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CellName   string      `protobuf:"bytes,1,opt,name=cell_name,json=cellName,proto3" json:"cell_name,omitempty"`
	Executable *Executable `protobuf:"bytes,2,opt,name=executable,proto3" json:"executable,omitempty"`
}

func (x *CellServiceStartRequest) Reset() {
	*x = CellServiceStartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_cell_v0_cell_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CellServiceStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellServiceStartRequest) ProtoMessage() {}

func (x *CellServiceStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_cell_v0_cell_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellServiceStartRequest.ProtoReflect.Descriptor instead.
func (*CellServiceStartRequest) Descriptor() ([]byte, []int) {
	return file_runtime_cell_v0_cell_proto_rawDescGZIP(), []int{6}
}

func (x *CellServiceStartRequest) GetCellName() string {
	if x != nil {
		return x.CellName
	}
	return ""
}

func (x *CellServiceStartRequest) GetExecutable() *Executable {
	if x != nil {
		return x.Executable
	}
	return nil
}

// / The response after starting an executable within a Cell.
type CellServiceStartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// / Return a pid as an int32 based on the pid_t type
	// / in various libc libraries.
	Pid int32 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
}

func (x *CellServiceStartResponse) Reset() {
	*x = CellServiceStartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_cell_v0_cell_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CellServiceStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellServiceStartResponse) ProtoMessage() {}

func (x *CellServiceStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_cell_v0_cell_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellServiceStartResponse.ProtoReflect.Descriptor instead.
func (*CellServiceStartResponse) Descriptor() ([]byte, []int) {
	return file_runtime_cell_v0_cell_proto_rawDescGZIP(), []int{7}
}

func (x *CellServiceStartResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// / Request to stop an executable at runtime.
type CellServiceStopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CellName       string `protobuf:"bytes,1,opt,name=cell_name,json=cellName,proto3" json:"cell_name,omitempty"`
	ExecutableName string `protobuf:"bytes,2,opt,name=executable_name,json=executableName,proto3" json:"executable_name,omitempty"`
}

func (x *CellServiceStopRequest) Reset() {
	*x = CellServiceStopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_cell_v0_cell_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CellServiceStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellServiceStopRequest) ProtoMessage() {}

func (x *CellServiceStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_cell_v0_cell_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellServiceStopRequest.ProtoReflect.Descriptor instead.
func (*CellServiceStopRequest) Descriptor() ([]byte, []int) {
	return file_runtime_cell_v0_cell_proto_rawDescGZIP(), []int{8}
}

func (x *CellServiceStopRequest) GetCellName() string {
	if x != nil {
		return x.CellName
	}
	return ""
}

func (x *CellServiceStopRequest) GetExecutableName() string {
	if x != nil {
		return x.ExecutableName
	}
	return ""
}

type CellServiceStopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CellServiceStopResponse) Reset() {
	*x = CellServiceStopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_runtime_cell_v0_cell_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CellServiceStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellServiceStopResponse) ProtoMessage() {}

func (x *CellServiceStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_cell_v0_cell_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellServiceStopResponse.ProtoReflect.Descriptor instead.
func (*CellServiceStopResponse) Descriptor() ([]byte, []int) {
	return file_runtime_cell_v0_cell_proto_rawDescGZIP(), []int{9}
}

var File_runtime_cell_v0_cell_proto protoreflect.FileDescriptor

var file_runtime_cell_v0_cell_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2f, 0x63, 0x65, 0x6c, 0x6c, 0x2f, 0x76,
	0x30, 0x2f, 0x63, 0x65, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x61, 0x75,
	0x72, 0x61, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x63, 0x65, 0x6c, 0x6c,
	0x2e, 0x76, 0x30, 0x22, 0x5c, 0x0a, 0x0a, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0xe2, 0x02, 0x0a, 0x04, 0x43, 0x65, 0x6c, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x63, 0x70, 0x75, 0x5f, 0x63, 0x70, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x70, 0x75, 0x43, 0x70, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x70, 0x75,
	0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x63,
	0x70, 0x75, 0x53, 0x68, 0x61, 0x72, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x70, 0x75, 0x5f,
	0x6d, 0x65, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x70, 0x75, 0x4d,
	0x65, 0x6d, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x70, 0x75, 0x5f, 0x71, 0x75, 0x6f, 0x74, 0x61,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x70, 0x75, 0x51, 0x75, 0x6f, 0x74, 0x61,
	0x12, 0x24, 0x0a, 0x0e, 0x6e, 0x73, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x5f, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x6e, 0x73, 0x53, 0x68, 0x61, 0x72,
	0x65, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0c, 0x6e, 0x73, 0x5f, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x5f, 0x75, 0x74, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x6e, 0x73,
	0x53, 0x68, 0x61, 0x72, 0x65, 0x55, 0x74, 0x73, 0x12, 0x20, 0x0a, 0x0c, 0x6e, 0x73, 0x5f, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x5f, 0x69, 0x70, 0x63, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a,
	0x6e, 0x73, 0x53, 0x68, 0x61, 0x72, 0x65, 0x49, 0x70, 0x63, 0x12, 0x20, 0x0a, 0x0c, 0x6e, 0x73,
	0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x5f, 0x70, 0x69, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0a, 0x6e, 0x73, 0x53, 0x68, 0x61, 0x72, 0x65, 0x50, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0c,
	0x6e, 0x73, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x5f, 0x6e, 0x65, 0x74, 0x18, 0x0e, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0a, 0x6e, 0x73, 0x53, 0x68, 0x61, 0x72, 0x65, 0x4e, 0x65, 0x74, 0x12, 0x26,
	0x0a, 0x0f, 0x6e, 0x73, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x5f, 0x63, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x6e, 0x73, 0x53, 0x68, 0x61, 0x72, 0x65,
	0x43, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x22, 0x4d, 0x0a, 0x1a, 0x43, 0x65, 0x6c, 0x6c, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x04, 0x63, 0x65, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x75, 0x72, 0x61, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x2e, 0x63, 0x65, 0x6c, 0x6c, 0x2e, 0x76, 0x30, 0x2e, 0x43, 0x65, 0x6c, 0x6c, 0x52,
	0x04, 0x63, 0x65, 0x6c, 0x6c, 0x22, 0x57, 0x0a, 0x1b, 0x43, 0x65, 0x6c, 0x6c, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x65, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x65, 0x6c, 0x6c, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x76, 0x32, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x63, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x56, 0x32, 0x22, 0x35,
	0x0a, 0x16, 0x43, 0x65, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x46, 0x72, 0x65,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x65, 0x6c, 0x6c,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x65, 0x6c,
	0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x43, 0x65, 0x6c, 0x6c, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x46, 0x72, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x79, 0x0a, 0x17, 0x43, 0x65, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63,
	0x65, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x65, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x65, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61,
	0x75, 0x72, 0x61, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x63, 0x65, 0x6c,
	0x6c, 0x2e, 0x76, 0x30, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x52,
	0x0a, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x2c, 0x0a, 0x18, 0x43,
	0x65, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x69, 0x64, 0x22, 0x5e, 0x0a, 0x16, 0x43, 0x65, 0x6c,
	0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x65, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x65, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x27, 0x0a, 0x0f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x65, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x43, 0x65, 0x6c,
	0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0xc0, 0x03, 0x0a, 0x0b, 0x43, 0x65, 0x6c, 0x6c, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x73, 0x0a, 0x08, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65,
	0x12, 0x31, 0x2e, 0x61, 0x75, 0x72, 0x61, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x2e, 0x63, 0x65, 0x6c, 0x6c, 0x2e, 0x76, 0x30, 0x2e, 0x43, 0x65, 0x6c, 0x6c, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e, 0x61, 0x75, 0x72, 0x61, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x2e, 0x63, 0x65, 0x6c, 0x6c, 0x2e, 0x76, 0x30, 0x2e, 0x43, 0x65, 0x6c, 0x6c,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x67, 0x0a, 0x04, 0x46, 0x72, 0x65,
	0x65, 0x12, 0x2d, 0x2e, 0x61, 0x75, 0x72, 0x61, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x2e, 0x63, 0x65, 0x6c, 0x6c, 0x2e, 0x76, 0x30, 0x2e, 0x43, 0x65, 0x6c, 0x6c, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x46, 0x72, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x2e, 0x2e, 0x61, 0x75, 0x72, 0x61, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x2e, 0x63, 0x65, 0x6c, 0x6c, 0x2e, 0x76, 0x30, 0x2e, 0x43, 0x65, 0x6c, 0x6c, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x46, 0x72, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x6a, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x2e, 0x2e, 0x61, 0x75,
	0x72, 0x61, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x63, 0x65, 0x6c, 0x6c,
	0x2e, 0x76, 0x30, 0x2e, 0x43, 0x65, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x61, 0x75,
	0x72, 0x61, 0x65, 0x2e, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x63, 0x65, 0x6c, 0x6c,
	0x2e, 0x76, 0x30, 0x2e, 0x43, 0x65, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x67,
	0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x2d, 0x2e, 0x61, 0x75, 0x72, 0x61, 0x65, 0x2e, 0x72,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x63, 0x65, 0x6c, 0x6c, 0x2e, 0x76, 0x30, 0x2e, 0x43,
	0x65, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x61, 0x75, 0x72, 0x61, 0x65, 0x2e, 0x72, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x63, 0x65, 0x6c, 0x6c, 0x2e, 0x76, 0x30, 0x2e, 0x43, 0x65,
	0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x49, 0x5a, 0x47, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x75, 0x72, 0x61, 0x65, 0x2d, 0x72, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x2f, 0x61, 0x75, 0x72, 0x61, 0x65, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x2f, 0x63, 0x65, 0x6c, 0x6c, 0x2f, 0x76, 0x30, 0x3b, 0x63, 0x65, 0x6c, 0x6c,
	0x76, 0x30, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_runtime_cell_v0_cell_proto_rawDescOnce sync.Once
	file_runtime_cell_v0_cell_proto_rawDescData = file_runtime_cell_v0_cell_proto_rawDesc
)

func file_runtime_cell_v0_cell_proto_rawDescGZIP() []byte {
	file_runtime_cell_v0_cell_proto_rawDescOnce.Do(func() {
		file_runtime_cell_v0_cell_proto_rawDescData = protoimpl.X.CompressGZIP(file_runtime_cell_v0_cell_proto_rawDescData)
	})
	return file_runtime_cell_v0_cell_proto_rawDescData
}

var file_runtime_cell_v0_cell_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_runtime_cell_v0_cell_proto_goTypes = []interface{}{
	(*Executable)(nil),                  // 0: aurae.runtime.cell.v0.Executable
	(*Cell)(nil),                        // 1: aurae.runtime.cell.v0.Cell
	(*CellServiceAllocateRequest)(nil),  // 2: aurae.runtime.cell.v0.CellServiceAllocateRequest
	(*CellServiceAllocateResponse)(nil), // 3: aurae.runtime.cell.v0.CellServiceAllocateResponse
	(*CellServiceFreeRequest)(nil),      // 4: aurae.runtime.cell.v0.CellServiceFreeRequest
	(*CellServiceFreeResponse)(nil),     // 5: aurae.runtime.cell.v0.CellServiceFreeResponse
	(*CellServiceStartRequest)(nil),     // 6: aurae.runtime.cell.v0.CellServiceStartRequest
	(*CellServiceStartResponse)(nil),    // 7: aurae.runtime.cell.v0.CellServiceStartResponse
	(*CellServiceStopRequest)(nil),      // 8: aurae.runtime.cell.v0.CellServiceStopRequest
	(*CellServiceStopResponse)(nil),     // 9: aurae.runtime.cell.v0.CellServiceStopResponse
}
var file_runtime_cell_v0_cell_proto_depIdxs = []int32{
	1, // 0: aurae.runtime.cell.v0.CellServiceAllocateRequest.cell:type_name -> aurae.runtime.cell.v0.Cell
	0, // 1: aurae.runtime.cell.v0.CellServiceStartRequest.executable:type_name -> aurae.runtime.cell.v0.Executable
	2, // 2: aurae.runtime.cell.v0.CellService.Allocate:input_type -> aurae.runtime.cell.v0.CellServiceAllocateRequest
	4, // 3: aurae.runtime.cell.v0.CellService.Free:input_type -> aurae.runtime.cell.v0.CellServiceFreeRequest
	6, // 4: aurae.runtime.cell.v0.CellService.Start:input_type -> aurae.runtime.cell.v0.CellServiceStartRequest
	8, // 5: aurae.runtime.cell.v0.CellService.Stop:input_type -> aurae.runtime.cell.v0.CellServiceStopRequest
	3, // 6: aurae.runtime.cell.v0.CellService.Allocate:output_type -> aurae.runtime.cell.v0.CellServiceAllocateResponse
	5, // 7: aurae.runtime.cell.v0.CellService.Free:output_type -> aurae.runtime.cell.v0.CellServiceFreeResponse
	7, // 8: aurae.runtime.cell.v0.CellService.Start:output_type -> aurae.runtime.cell.v0.CellServiceStartResponse
	9, // 9: aurae.runtime.cell.v0.CellService.Stop:output_type -> aurae.runtime.cell.v0.CellServiceStopResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_runtime_cell_v0_cell_proto_init() }
func file_runtime_cell_v0_cell_proto_init() {
	if File_runtime_cell_v0_cell_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_runtime_cell_v0_cell_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Executable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_cell_v0_cell_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cell); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_cell_v0_cell_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CellServiceAllocateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_cell_v0_cell_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CellServiceAllocateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_cell_v0_cell_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CellServiceFreeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_cell_v0_cell_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CellServiceFreeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_cell_v0_cell_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CellServiceStartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_cell_v0_cell_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CellServiceStartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_cell_v0_cell_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CellServiceStopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_runtime_cell_v0_cell_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CellServiceStopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_runtime_cell_v0_cell_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtime_cell_v0_cell_proto_goTypes,
		DependencyIndexes: file_runtime_cell_v0_cell_proto_depIdxs,
		MessageInfos:      file_runtime_cell_v0_cell_proto_msgTypes,
	}.Build()
	File_runtime_cell_v0_cell_proto = out.File
	file_runtime_cell_v0_cell_proto_rawDesc = nil
	file_runtime_cell_v0_cell_proto_goTypes = nil
	file_runtime_cell_v0_cell_proto_depIdxs = nil
}
