# ---------------------------------------------------------------------------- #
#        Apache 2.0 License Copyright © 2022-2023 The Aurae Authors            #
#                                                                              #
#                +--------------------------------------------+                #
#                |   █████╗ ██╗   ██╗██████╗  █████╗ ███████╗ |                #
#                |  ██╔══██╗██║   ██║██╔══██╗██╔══██╗██╔════╝ |                #
#                |  ███████║██║   ██║██████╔╝███████║█████╗   |                #
#                |  ██╔══██║██║   ██║██╔══██╗██╔══██║██╔══╝   |                #
#                |  ██║  ██║╚██████╔╝██║  ██║██║  ██║███████╗ |                #
#                |  ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝ |                #
#                +--------------------------------------------+                #
#                                                                              #
#                         Distributed Systems Runtime                          #
#                                                                              #
# ---------------------------------------------------------------------------- #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
#                                                                              #
# ---------------------------------------------------------------------------- #
#
# The primary Aurae test container, used to cache and support the GitHub
# builds.
#
# This container image is NOT intended to run Aurae in production.
# For internal builds of auraed use Dockerfile.build
#
# syntax = docker/dockerfile:1.4
FROM rust:1-slim-bullseye as main
LABEL org.opencontainers.image.source https://github.com/aurae-runtime/aurae

## Define ARGs
ARG CACHE_VERSION=v0
ARG BUF_VERSION=1.11.0
ARG VALE_VERSION=2.21.3
ARG PROTOC_VERSION=1.5.1

## Install packages
RUN  apt-get update && \
    apt-get install -y --no-install-recommends \
    curl \
    make \
    musl-tools \
    protobuf-compiler \
    git \
    python3-pip \
    libssl-dev \
    openssl \
    pkg-config
RUN rm -rf /var/lib/apt/lists/*

## Setup Rust
RUN rustup component add clippy
RUN rustup +nightly target add x86_64-unknown-linux-musl
RUN rustup target add x86_64-unknown-linux-musl

## Setup protoc-gen-doc
RUN curl  -O -J -L https://github.com/pseudomuto/protoc-gen-doc/releases/download/v${PROTOC_VERSION}/protoc-gen-doc_${PROTOC_VERSION}_linux_amd64.tar.gz && \
    tar -xzf protoc-gen-doc_${PROTOC_VERSION}_linux_amd64.tar.gz && \
    chmod +x protoc-gen-doc && \
    mv protoc-gen-doc /usr/local/bin/protoc-gen-doc && \
    rm protoc-gen-doc_${PROTOC_VERSION}_linux_amd64.tar.gz

## Setup Buf
RUN curl -sSL \
    "https://github.com/bufbuild/buf/releases/download/v${BUF_VERSION}/buf-$(uname -s)-$(uname -m)" \
    -o "/usr/local/bin/buf" && \
    chmod +x "/usr/local/bin/buf"

## Setup Vale
RUN curl -sSl -J -L "https://github.com/errata-ai/vale/releases/download/v${VALE_VERSION}/vale_${VALE_VERSION}_Linux_64-bit.tar.gz" \
    -o vale.tar.gz && \
    tar -xvzf vale.tar.gz -C bin && \
    mv bin/vale /usr/local/bin/vale && \
    rm vale.tar.gz


## Setup cargo-udeps
RUN cargo install cargo-udeps
RUN cargo install cargo-deny

WORKDIR /aurae