# ---------------------------------------------------------------------------- #
#                                                                              #
#                +--------------------------------------------+                #
#                |   █████╗ ██╗   ██╗██████╗  █████╗ ███████╗ |                #
#                |  ██╔══██╗██║   ██║██╔══██╗██╔══██╗██╔════╝ |                #
#                |  ███████║██║   ██║██████╔╝███████║█████╗   |                #
#                |  ██╔══██║██║   ██║██╔══██╗██╔══██║██╔══╝   |                #
#                |  ██║  ██║╚██████╔╝██║  ██║██║  ██║███████╗ |                #
#                |  ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝ |                #
#                +--------------------------------------------+                #
#                                                                              #
#                         Distributed Systems Runtime                          #
#                                                                              #
# ---------------------------------------------------------------------------- #
#                                                                              #
#  Copyright 2022 - 2024, the Aurae contributors                               #
#  SPDX-License-Identifier: Apache-2.0                                         #
#                                                                              #
# ---------------------------------------------------------------------------- #
#
# This will check the documentation, and deploy the https://aurae.io website
# from the current code base upon merge -> main.
#
# This build check will introduce confidence for the following:
#
# - That the documentation is updated and passes our spelling checks.
# - That the website is deployed with a fresh copy of the new docs.
#
# When this build passes we should have confidence that our documentation is
# updated on the website complete with best practices.
#
name: "Deploy Website Documentation (291) [aurae:builder:tester-latest]"
on:
 push:
   branches: main

jobs:
  build-container:
    uses: ./.github/workflows/200-aurae-builder-image-docker-build-tester.yml
  deploy:
    runs-on: ubuntu-latest
    needs: build-container
    container:
      image: ghcr.io/${{ github.repository }}/aurae-builder:tester-latest
      credentials:
        username:  ${{ github.actor }}
        password:  ${{ secrets.GITHUB_TOKEN }}
    steps:
        - uses: actions/checkout@v3
        ## Configure Git
        # This fixes a current issue with git and dubious ownership of folders
        # https://github.com/actions/runner-images/issues/6775
        - run: git config --global --add safe.directory /__w/aurae/aurae
        - uses: actions/setup-python@v2
          with:
            python-version: 3.x
        - name: Install mkdocs-material [aurae-builder:builder-latest]
          run: |
            pip install mkdocs-material
        - name: Build Documentation [make docs]
          run: make docs
        - name: Deploy 'aurae.io' Website [mkdocs gh-deploy]
          run: mkdocs gh-deploy --force